# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-deploy:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout:
          path: ~/project
      - docker/check
      - docker/build:
          dockerfile: sls-base/Dockerfile
          image: mbuzi/mbuzi-cicd:v0.0.1
      - docker/push:
          image: mbuzi/mbuzi-cicd
          tag: v0.0.1

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build-deploy:
          context: context-mbuzi-dev
          requires:
            - build
          filters:
            tags:
              only: /(^v\d+.*)/
            branches:
              only: /(^master)/