# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  docker: circleci/docker@1.0.1

jobs:
  build:
    executor: docker/docker
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: mbuzi/mbuzi-cicd:v0.0.1
  deploy:
    executor: docker/docker
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: mbuzi/mbuzi-cicd:v0.0.1
      - docker/push:
          image: mbuzi/mbuzi-cicd:v0.0.1


workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build:
          context: context-mbuzi-dev
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          context: context-mbuzi-dev
          requires:
            - build
          filters:
            tags:
              only: /(^v\d+.*)/
            branches:
              only: /(^master)/